---

root: true

plugins:
  - jest
  - babel
  - jest-dom
  - testing-library

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:jest-dom/recommended'
  - 'plugin:testing-library/dom'

rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
